name: mental_health_app
description: A mental health companion app with AI chat support.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2
  curved_navigation_bar: ^1.0.3
  flutter_staggered_animations: ^1.1.1
  image_picker: ^1.0.7
  cupertino_icons: ^1.0.8
  http: ^1.2.0

  # Firebase - Cập nhật lên phiên bản mới nhất
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Regular.ttf
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 700
